Remove username
tamu-edu-students/csce-606-autograder-frontend pull request #39
Opened 2024-10-05 21:13 UTC by riddhighate-tamu

Remove username from the user model

## Description
1. Remove the username attribute from User model.
2. Change username to name in all the test files.

## How has this been tested?
1. Executed bundle exec rspec and bundle exec cucumber to verify that all the tests are successful.

## Screenshots (if appropriate):

## Checklist:

- [x] Zero `rubocop` violations
- [x] My code receives an "A" when `rubycritic` is run
- [x] >90% test coverage of my changes
- [x] All new and existing tests passed

2024-10-05 21:18 UTC, maxsmith271346 commented
Were you able to run the app locally without any issues?

2024-10-05 21:37 UTC, masarkar-tamu approved these changes

2024-10-05 21:44 UTC, maxsmith271346 requested changes
Were you able to run the app locally without any issues?

2024-10-06 00:52 UTC, maxsmith271346 approved these changes

2024-10-06 00:53 UTC, maxsmith271346 commented
App was confirmed to run locally during standup

2024-10-06 02:19 UTC, merged