Feature/61 consitent button styling
tamu-edu-students/csce-606-autograder-frontend pull request #78
Opened 2024-10-16 20:51 UTC by gonzalezpear8

## Description

Changed the CSS files and formatting of the links/buttons/dropdown boxes/text fields
## How has this been tested?
This was tested by running the server locally and seeing the changes. 

## Screenshots (if appropriate):
![image](https://github.com/user-attachments/assets/b487b681-d40b-460f-8ce1-5e46ed1bb415)
![image](https://github.com/user-attachments/assets/69003200-db31-4322-8016-12b0ad4f971d)
![image](https://github.com/user-attachments/assets/9709a270-3aef-400d-a1c9-e554e4b27106)
![image](https://github.com/user-attachments/assets/3707d60a-a795-452a-919c-a0807b64ecf3)
![image](https://github.com/user-attachments/assets/2543557f-1bfc-42a8-aa3d-e8c95785ace3)
![image](https://github.com/user-attachments/assets/1161597b-5543-4c0a-afce-85d2e57ec15c)

## Checklist:

- [ ] Zero `rubocop` violations
- [ ] My code receives an "A" when `rubycritic` is run
- [ ] >90% test coverage of my changes
- [ ] All new and existing tests passed

2024-10-17 01:36 UTC, maxsmith271346 requested changes

2024-10-17 01:36 UTC, maxsmith271346 commented on app/views/assignments/_assignment.html.erb
> +    <strong>Assignment dsafdafdasfd:</strong>
Please change this to `Assignment Name`

2024-10-17 06:09 UTC, maxsmith271346 approved these changes

2024-10-17 06:14 UTC, maxsmith271346 requested changes
There is a `.feature` file associated with this feature.  Please use `git checkout <branch> <filename>` to get this into your branch, then write the necessary step definitions.

2024-10-17 20:07 UTC, riddhighate-tamu commented
For the consistent styling feature, go to `sprint2_features` branch. There is a file called `features/consistent_styling.feature`, only pull this file in your branch and complete the scenarios for it.

2024-10-18 04:27 UTC, maxsmith271346 commented
@gonzalezpear8 Is there any update on this?

2024-10-18 16:47 UTC, riddhighate-tamu commented
Can you push the feature file and the related cucumber steps?

2024-10-18 16:47 UTC, riddhighate-tamu commented
Please take pull from the `main` branch and resolve the conflicts.

2024-10-19 03:17 UTC, maxsmith271346 requested changes

2024-10-19 03:17 UTC, maxsmith271346 commented on app/views/assignments/show.html.erb
> +            <%= button_to "Destroy this test", assignment_test_path(@assignment, @test), method: :delete, data: { confirm: "Are you sure?", turbo: false }, class: "btn btn-danger" %>
Please change this to say "Delete Test"

2024-10-19 04:19 UTC, riddhighate-tamu approved these changes

2024-10-19 04:20 UTC, gonzalezpear8 commented
![image](https://github.com/user-attachments/assets/0dba9049-b76a-4de2-814e-37e91dfda275)

2024-10-19 04:21 UTC, masarkar-tamu approved these changes

2024-10-19 04:23 UTC, merged